### PR TITLE
Scala 3 support

### PR DESCRIPTION
**Pull request by OndrejSpanel**
This PR makes necessary changes to cross-compile on Scala 3.

While Scala 3 projects can use 2.13 libraries, this is problematic because of transitional dependencies to things like _scala-xml_.

Support for Scala 2.11 was dropped because of _specs2_, which does not exist in a version which is available for both 2.11 and 3.x.

### CODE REVIEW

**Comment by benhutchison** [comment]
Thanks @OndrejSpanel, I'm out in nature this weekend without laptop but will merge and publish Sunday night

**Comment by OndrejSpanel** [comment]
Thanks, no hurry, enjoy your nature time. 🌳🌲

**Comment by benhutchison** [comment]
Actually, I'm also hitting a compile error:
```
[info] compiling 34 Scala sources to /Users/ben/workspace/ScalaSwingContrib/target/scala-3.1.2/classes ...
[error] -- [E008] Not Found Error: /Users/ben/workspace/ScalaSwingContrib/src/main/scala/scalaswingcontrib/TransferHandlerRow.scala:6:13 
[error] 6 |import javax.activation.{DataHandler, ActivationDataFlavor}
[error]   |       ^^^^^^^^^^^^^^^^
[error]   |       value activation is not a member of javax
```

```
> java -version
openjdk version "17.0.2" 2022-01-18
```

@OndrejSpanel I've just done a few minutes reading on the issue, but afaict it requires a rename ~javax~jakarta. Are you OK if I do that across the project, or prefer another approach?

**Comment by OndrejSpanel** [comment]
I think I was compiling against Java 8. I will check how to solve it, I think I have already seen this in another project.

**Comment by benhutchison** [comment]
Ive just published 1.9. I chose to bypass some spec2 tests which seem to be using features no longer supported. At this late stage in the library life, I dont think the tests were adding much value.

**Pull request merged**
